# Generated by Django 3.0.5 on 2020-04-16 08:34

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200407_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=post.models.upload_location),
        ),
    ]
