# Generated by Django 3.0.5 on 2020-06-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
