# Generated by Django 3.0.5 on 2020-06-17 14:31

from django.db import migrations, models
import django.db.models.deletion
import uploadImage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0006_remove_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to=uploadImage.models.upload_location)),
                ('post', models.ForeignKey(blank=None, on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
    ]
